version: "3.8"
services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # redis:
  #   image: redis
  #   volumes:
  #     - ./redis_data:/data
