version: "3.6"
services:
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: family
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    image: deepbio-family:latest
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    command: >
      python3 app.py
    depends_on:
      - "db"
